apiVersion: v1
kind: Secret
metadata:
  name: mongo-backup-secret
type: Opaque
stringData:
  MONGO_URI: mongodb://mangodb-svc:27017
  MINIO_ENDPOINT: http://minio-service.default.svc.cluster.local:9000
  MINIO_BUCKET: demo
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin

